baseURL = 'https://shermanrose.uk'
languageCode = 'en-gb'
title = "Shermans's Notes"
paginate = 5
theme = "hugo-geekdoc"
pluralizeListTitles = false
ignoreFiles = ['templates/*']

[params]
  geekdocCollapseAllSections = true
  # Geekdoc required configuration
  pygmentsUseClasses = false
  pygmentsCodeFences = true
  disablePathToLower = true

  # Required if you want to render robots.txt template
  enableRobotsTXT = true

# Needed for mermaid shortcodes
[markup]
  [markup.highlight]
    anchorLineNos = false  
    codeFences = true 
    guessSyntax = true
    lineAnchors = 'l'
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokai'
    tabWidth = 2
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9